export const WeatherCodes = {

  "0": {"name":"despejado", "img":"despejado"},
  "1": {"name":"mayormente despejado", "img":"despejado"}, 
  "2": {"name":"parcialmente nublado", "img":"parcial_nublado"}, 
  "3": {"name":"nublado", "img":"nublado"},
  "45": {"name":"niebla", "img":"niebla"}, 
  "48": {"name":"niebla con escarcha", "img":"niebla"},
  "51": {"name":"llovizna ligera", "img":"llovizna_ligera"}, 
  "53": {"name":"llovizna moderada", "img":"llovizna_moderada"}, 
  "55": {"name":"llovizna densa", "img":"llovizna_densa"},
  "56": {"name":"llovizna helada ligera", "img":"llovizna_ligera"}, 
  "57": {"name":"llovizna helada densa", "img":"llovizna_densa"},
  "61": {"name":"lluvia leve", "img":"lluvia_leve"}, 
  "63": {"name":"lluvia moderada", "img":"lluvia_moderada"}, 
  "65": {"name":"lluvia fuerte", "img":"lluvia_fuerte"},
  "66": {"name":"lluvia helada ligera", "img":"lluvia_leve"}, 
  "67": {"name":"lluvia helada fuerte", "img":"lluvia_fuerte"},
  "71": {"name":"nieve ligera", "img":"nieve_ligera"}, 
  "73": {"name":"nieve moderada", "img":"nieve_moderada"}, 
  "75": {"name":"nieve densa", "img":"nieve_densa"},
  "77": {"name":"granizo", "img":"granizo"},
  "80": {"name":"chubascos leves", "img":"chubascos_leves"}, 
  "81": {"name":"chubascos moderados", "img":"chubascos_moderados"}, 
  "82": {"name":"chubascos violentos", "img":"chubascos_violentos"},
  "85": {"name":"chubascos de nieve ligeros", "img":"chubascos_nieve_ligeros"}, 
  "86": {"name":"chubascos de nieve fuertes", "img":"chubascos_nieve_fuertes"},
  "95": {"name":"tormenta leve o moderada", "img":"tormenta"},
  "96": {"name":"tormenta con granizo leve", "img":"tormenta_granizo_leve"}, 
  "99": {"name":"tormenta con granizo fuerte", "img":"tormenta_granizo_fuerte"}
  
};