export const WeaterCodes = {
  0: 'despejado',
  1: 'mayormente despejado', 
  2: 'parcialmente nublado', 
  3: 'nublado',
  45: 'niebla', 
  48: 'niebla con escarcha',
  51: 'llovizna ligera', 
  53: 'llovizna moderada', 
  55: 'llovizna densa',
  56: 'llovizna helada ligera', 
  57: 'llovizna helada densa',
  61: 'lluvia leve', 
  63: 'lluvia moderada', 
  65: 'lluvia fuerte',
  66: 'lluvia helada ligera', 
  67: 'lluvia helada fuerte',
  71: 'nieve ligera', 
  73: 'nieve moderada', 
  75: 'nieve densa',
  77: 'granizo',
  80: 'chubascos leves', 
  81: 'chubascos moderados', 
  82: 'chubascos violentos',
  85: 'chubascos de nieve ligeros', 
  86: 'chubascos de nieve fuertes',
  95: 'tormenta leve o moderada',
  96: 'tormenta con granizo leve', 
  99: 'tormenta con granizo fuerte'
};