
export const WeatherCodes = {
  0: {alt:'despejado', img:'despejado'},
  1: {alt:'mayormente despejado', img:'despejado'}, 
  2: {alt:'parcialmente nublado', img:'parcial_nublado'}, 
  3: {alt:'nublado', img:'nublado'},
  45: {alt:'niebla', img:'niebla'}, 
  48: {alt:'niebla con escarcha', img:'niebla'},
  51: {alt:'llovizna ligera', img:'llovizna_ligera'}, 
  53: {alt:'llovizna moderada', img:'llovizna_moderada'}, 
  55: {alt:'llovizna densa', img:'llovizna_densa'},
  56: {alt:'llovizna helada ligera', img:'llovizna_helada_ligera'}, 
  57: {alt:'llovizna helada densa', img:'llovizna_helada_densa'},
  61: {alt:'lluvia leve', img:'lluvia_leve'}, 
  63: {alt:'lluvia moderada', img:'lluvia_moderada'}, 
  65: {alt:'lluvia fuerte', img:'lluvia_fuerte'},
  66: {alt:'lluvia helada ligera', img:'lluvia_helada_ligera'}, 
  67: {alt:'lluvia helada fuerte', img:'lluvia_helada_fuerte'},
  71: {alt:'nieve ligera', img:'nieve_ligera'}, 
  73: {alt:'nieve moderada', img:'nieve_moderada'}, 
  75: {alt:'nieve densa', img:'nieve_densa'},
  77: {alt:'granizo', img:'granizo'},
  80: {alt:'chubascos leves', img:'chubascos_leves'}, 
  81: {alt:'chubascos moderados', img:'chubascos_moderados'}, 
  82: {alt:'chubascos violentos', img:'chubascos_violentos'},
  85: {alt:'chubascos de nieve ligeros', img:'chubascos_nieve_ligeros'}, 
  86: {alt:'chubascos de nieve fuertes', img:'chubascos_nieve_fuertes'},
  95: {alt:'tormenta leve o moderada', img:'tormenta'},
  96: {alt:'tormenta con granizo leve', img:'tormenta_granizo_leve'}, 
  99: {alt:'tormenta con granizo fuerte', img:'tormenta_granizo_fuerte'}
};